name: 🚀 Publish Android package
run-name: Publish ${{ inputs.projectName }} Android package

on:
  workflow_call:
    inputs:
      projectName:
        description: 'The name of the project'
        required: false
        type: string
      projectFile:
        description: 'The project file path'
        required: true
        type: string
      version:
        description: 'Package version suffix'
        required: true
        type: string
      environment:
        description: 'The publish environment'
        default: release
        type: string
      configuration:
        description: 'The publish configuration'
        default: Release
        type: string

jobs:
  deploy:
    name: Android
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
    - name: Checkout the source repository from Git
      uses: actions/checkout@v4

    # https://github.com/actions/setup-dotnet
    - name: Get .NET externals
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        dotnet-quality: 'ga'
  
    - name: Publish Android package
      run: |
        echo "Project Name: ${{ inputs.projectName }}";
        echo "Project File: $projectFile";
        echo "Project Version: $buildVersion";
        dotnet workload restore;
        dotnet publish $projectFile -c $configuration -f $targetFramework /p:Version=$buildVersion /p:AndroidPackageFormats=$androidPackageFormats -o $publishOutputFolder --nologo;
      env:
        projectFile: '${{ inputs.projectFile }}'
        buildVersion: '${{ inputs.version }}'
        configuration: ${{ inputs.configuration }}
        targetFramework: "net8.0-android"
        androidPackageFormats: "apk" # "aab;apk"
        publishOutputFolder: "publish"

    - name: Markdown workflow job summary
      run: echo "### ${{ inputs.projectName }} ${{ inputs.version }} apk published" >> $GITHUB_STEP_SUMMARY
