name: Release
run-name: Publish release branch or SemVer tags

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'
    branches:
      - release/**

# Cancel any other running workflows with the same ID
concurrency:
  group: cd-release-${{ github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
jobs:
  version:
    uses: ./.github/workflows/_version.yml

  publish:
    if: ${{ github.event_name != 'pull_request' }}
    needs: version
    uses: ./.github/workflows/_publish.yml
    with:
      projectName: ${{ needs.version.outputs.projectName }}
      projectFile: ${{ needs.version.outputs.projectFiles }}
      version: ${{ needs.version.outputs.semVer }}
    secrets: inherit
